### ISSUE TITLE
Is there a way to detect if Five9 CTI is loaded?

### ISSUE THREAD

**Issue by volomike** [Five9DeveloperProgram/Five9CTISample#2]
In doing work between a developer and production environment, I'm trying to see if there's a quick way to determine if Five9 CTI is loaded. I *think* I came up with a way in my PHP (before the HTML and Javascript runs) to see if Five9 CTI is loaded. It looks like the following:

    <?php
    $view->FIVE9 = TRUE;
    $bDisplayErrors = ini_get('display_errors');
    ini_set('display_errors','Off');
    $sIgnore = file_get_contents('http://localhost:8080/agent/v2') or $view->FIVE9 = FALSE;
    ini_set('display_errors',$bDisplayErrors);
    ?>

There's two problems with this. First, it floods my Apache error log with the file_get_contents() call failing. Second, it slows down the system greatly and is just not the most efficient way to check if Five9 CTI is loaded.

What's your advice so that I can test? See, without testing if CTI is loaded, when I try to do a connection, your script causes the Javascript console to run a loop about the connection failure, and I couldn't find a way to turn that loop off.

**Comment by craigschmitt** [comment]
The connection loop is by design; we want our script to attempt a re-connection to CTI Web Services until it is successful. There's really no way around the continual polling for CTI WS as we have no other mechanism for determining if it is available. The console logging can be commented out if you find it excessive.
