### ISSUE TITLE
Does this work on IE ?

### ISSUE THREAD

**Issue by darkpssngr** [Five9DeveloperProgram/Five9CTISample#4]

**Comment by joshso** [comment]
You didn't note which version of IE, so I'll presume IE11. That version introduced a more comprehensive security model around mixed content, which blocked this library. There was no configuration we could find to allow compatibility.

We were eventually able to make it work by writing additional code and hosting on a web server: essentially an HTTP proxy of sorts. It was outside the scope of this example so we did not commit. Since then Five9 debuted our 'Plus' integrations which use a different API. This sample is only for the previous 'Stateless' architecture. We encourage customers writing new integrations to move to the Plus adapter first and integrate there.

**Comment by darkpssngr** [comment]
I was trying it on IE10.  I'm getting a cors preflight error (SEC7118 and SEC7119). And chrome has an extension does something similar exist for IE or using the Agent toolkit is enough?
Also can you point me to the documentaion of the 'Plus' adapter.

**Comment by joshso** [comment]
Once [logged in](https://login.five9.com), click Customer Support then Documentation.

Plus Adapter supports a minimum of IE11.
